export default {
  products: [
    {
      _id: '1',
      name: 'Pup Puffs',
      category: 'Treats',
      image: '/images/PupPuffs.jpg',
      price: 60,
      brand: 'Great Choice',
      type: 'Food',
    },
    {
      _id: '2',
      name: 'Rocabar',
      category: 'Collars',
      image: '/images/RocabarCollar.jpg',
      price: 50,
      brand: 'Hermes',
      type: 'Accessories',
    },
    {
      _id: '3',
      name: 'Tasty Minis',
      category: 'Treats',
      image: '/images/TastyMinis.jpg',
      price: 70,
      brand: 'Pedigree',
      type: 'Food',
    }, {
      _id: '4',
      name: 'Leather Collar',
      category: 'Collars',
      image: '/images/LeatherCollar.jpg',
      price: 70,
      brand: 'Adityna',
      type: 'Accessories',
    }, {
      _id: '5',
      name: 'Flat Out Leash',
      category: 'Leashes',
      image: '/images/FlatOutLeash.jpg',
      price: 70,
      brand: 'Ruffwear',
      type: 'Accessories',
    }, {
      _id: '6',
      name: 'Nylon Leash',
      category: 'Leashes',
      image: '/images/NylonLeash.jpg',
      price: 70,
      brand: 'PetSafe',
      type: 'Accessories',
    }, {
      _id: '7',
      name: 'Spiked Collar',
      category: 'Collars',
      image: '/images/SpikedCollar.jpg',
      price: 70,
      brand: 'Vova',
      type: 'Accessories',
    },
  ]
}